/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Site.glb')
  const { actions, names } = useAnimations(animations, group)
  console.log(names)

  useEffect(()=>{

    actions[names[0]].reset().fadeIn(2.5).play()
    actions[names[1]].reset().fadeIn(2.5).play()
    actions[names[2]].reset().fadeIn(2.5).play()
    actions[names[3]].reset().fadeIn(2.5).play()
    actions[names[4]].reset().fadeIn(2.5).play()
    actions[names[5]].reset().fadeIn(2.5).play()
    actions[names[6]].reset().fadeIn(2.5).play()
    actions[names[7]].reset().fadeIn(2.5).play()
    actions[names[8]].reset().fadeIn(2.5).play()
    actions[names[9]].reset().fadeIn(2.5).play()
    actions[names[10]].reset().fadeIn(2.5).play()
    actions[names[11]].reset().fadeIn(2.5).play()
    actions[names[12]].reset().fadeIn(2.5).play()

  },[])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Tela_3"
          castShadow
          receiveShadow
          geometry={nodes.Tela_3.geometry}
          material={materials['Base Screen 01']}
          position={[0, 0, -0.01]}
        />
        <mesh
          name="Tela_7"
          castShadow
          receiveShadow
          geometry={nodes.Tela_7.geometry}
          material={materials['Base Screen 02']}
          position={[0, 0, -0.01]}
        />
        <mesh
          name="Tela_6"
          castShadow
          receiveShadow
          geometry={nodes.Tela_6.geometry}
          material={materials['Base Screen 03']}
          position={[0, 0, -0.01]}
        />
        <mesh
          name="Tela_5"
          castShadow
          receiveShadow
          geometry={nodes.Tela_5.geometry}
          material={materials['Base Screen 04']}
          position={[0, 0, -0.01]}
        />
        <mesh
          name="Tela_4"
          castShadow
          receiveShadow
          geometry={nodes.Tela_4.geometry}
          material={materials['Base Screen 05']}
          position={[0, 0, -0.01]}
        />
        <mesh
          name="Tela_2"
          castShadow
          receiveShadow
          geometry={nodes.Tela_2.geometry}
          material={materials['Base Screen 06']}
          position={[0, 0, -0.01]}
        />
        <mesh
          name="Tela_1"
          castShadow
          receiveShadow
          geometry={nodes.Tela_1.geometry}
          material={materials['Base Screen 07']}
        />
        <mesh
          name="Tela_8"
          castShadow
          receiveShadow
          geometry={nodes.Tela_8.geometry}
          material={materials['Base Screen 08']}
          position={[0, 0, -0.01]}
        />
        <mesh
          name="Monitor"
          castShadow
          receiveShadow
          geometry={nodes.Monitor.geometry}
          material={materials.Plastico}
          position={[0, 0.208, -0.127]}
        />
        <mesh
          name="Tentaculo"
          castShadow
          receiveShadow
          geometry={nodes.Tentaculo.geometry}
          material={materials.Tentaculo}
          position={[0.156, 0.256, -0.119]}
          scale={0.27}
        />
        <mesh
          name="Post_It"
          castShadow
          receiveShadow
          geometry={nodes.Post_It.geometry}
          material={materials.Papel}
          position={[0, 0, -0.001]}
        />
        <mesh
          name="Donut"
          castShadow
          receiveShadow
          geometry={nodes.Donut.geometry}
          material={materials.Donut}
          position={[-0.187, 0.324, -0.119]}
          rotation={[0, 0, 0.461]}
          scale={0.051}
        />
        <group name="Plane" position={[0, 0.007, 0.027]} scale={[0.153, 0.153, 0.067]}>
          <mesh
            name="Mesh_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_2.geometry}
            material={materials['Mousepad Interior']}
          />
          <mesh
            name="Mesh_3"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_3.geometry}
            material={materials['Mousepad Borda']}
          />
        </group>
        <mesh
          name="Cobertura"
          castShadow
          receiveShadow
          geometry={nodes.Cobertura.geometry}
          material={materials.Cobertura}
          position={[-0.187, 0.324, -0.119]}
          rotation={[0, 0, 0.461]}
          scale={0.051}>
          <mesh
            name="GN_Instance"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance.geometry}
            material={materials.Material}
            position={[0.249, 0.242, 0.256]}
            scale={10}
          />
          <mesh
            name="GN_Instance_1"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_1.geometry}
            material={materials.Material}
            position={[0.092, 0.161, 0.545]}
            scale={10}
          />
          <mesh
            name="GN_Instance_2"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_2.geometry}
            material={materials.Material}
            position={[-0.544, 0.106, 0.007]}
            scale={10}
          />
          <mesh
            name="GN_Instance_3"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_3.geometry}
            material={materials.Material}
            position={[0.004, 0.204, 0.501]}
            scale={10}
          />
          <mesh
            name="GN_Instance_4"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_4.geometry}
            material={materials.Material}
            position={[-0.516, 0.162, -0.072]}
            scale={10}
          />
          <mesh
            name="GN_Instance_5"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_5.geometry}
            material={materials.Material}
            position={[0.244, 0.246, 0.284]}
            scale={10}
          />
          <mesh
            name="GN_Instance_6"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_6.geometry}
            material={materials.Material}
            position={[-0.529, 0.147, -0.09]}
            scale={10}
          />
          <mesh
            name="GN_Instance_7"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_7.geometry}
            material={materials.Material}
            position={[-0.464, 0.191, 0]}
            scale={10}
          />
          <mesh
            name="GN_Instance_8"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_8.geometry}
            material={materials.Material}
            position={[-0.502, 0.176, -0.09]}
            scale={10}
          />
          <mesh
            name="GN_Instance_9"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_9.geometry}
            material={materials.Material}
            position={[0.552, 0.147, -0.047]}
            scale={10}
          />
          <mesh
            name="GN_Instance_10"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_10.geometry}
            material={materials.Material}
            position={[-0.432, 0.214, -0.021]}
            scale={10}
          />
          <mesh
            name="GN_Instance_11"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_11.geometry}
            material={materials.Material}
            position={[0.557, 0.127, -0.079]}
            scale={10}
          />
          <mesh
            name="GN_Instance_12"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_12.geometry}
            material={materials.Material}
            position={[-0.387, 0.236, -0.063]}
            scale={10}
          />
          <mesh
            name="GN_Instance_13"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_13.geometry}
            material={materials.Material}
            position={[0.487, 0.207, -0.079]}
            scale={10}
          />
          <mesh
            name="GN_Instance_14"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_14.geometry}
            material={materials.Material}
            position={[0.531, 0.177, -0.025]}
            scale={10}
          />
          <mesh
            name="GN_Instance_15"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_15.geometry}
            material={materials.Material}
            position={[0.483, 0.212, 0.001]}
            scale={10}
          />
          <mesh
            name="GN_Instance_16"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_16.geometry}
            material={materials.Material}
            position={[0.42, 0.229, -0.002]}
            scale={10}
          />
          <mesh
            name="GN_Instance_17"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_17.geometry}
            material={materials.Material}
            position={[0.359, 0.229, -0.006]}
            scale={10}
          />
          <mesh
            name="GN_Instance_18"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_18.geometry}
            material={materials.Material}
            position={[0.347, 0.231, -0.031]}
            scale={10}
          />
          <mesh
            name="GN_Instance_19"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_19.geometry}
            material={materials.Material}
            position={[0.316, 0.225, -0.029]}
            scale={10}
          />
          <mesh
            name="GN_Instance_20"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_20.geometry}
            material={materials.Material}
            position={[-0.345, 0.239, -0.058]}
            scale={10}
          />
          <mesh
            name="GN_Instance_21"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_21.geometry}
            material={materials.Material}
            position={[-0.349, 0.232, -0.004]}
            scale={10}
          />
          <mesh
            name="GN_Instance_22"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_22.geometry}
            material={materials.Material}
            position={[0.554, 0.042, -0.191]}
            scale={10}
          />
          <mesh
            name="GN_Instance_23"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_23.geometry}
            material={materials.Material}
            position={[-0.289, 0.221, 0.004]}
            scale={10}
          />
          <mesh
            name="GN_Instance_24"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_24.geometry}
            material={materials.Material}
            position={[-0.263, 0.219, -0.05]}
            scale={10}
          />
          <mesh
            name="GN_Instance_25"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_25.geometry}
            material={materials.Material}
            position={[0.537, 0.074, -0.211]}
            scale={10}
          />
          <mesh
            name="GN_Instance_26"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_26.geometry}
            material={materials.Material}
            position={[0.037, 0.208, 0.498]}
            scale={10}
          />
          <mesh
            name="GN_Instance_27"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_27.geometry}
            material={materials.Material}
            position={[0.578, 0.025, -0.135]}
            scale={10}
          />
          <mesh
            name="GN_Instance_28"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_28.geometry}
            material={materials.Material}
            position={[0.56, 0.078, -0.147]}
            scale={10}
          />
          <mesh
            name="GN_Instance_29"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_29.geometry}
            material={materials.Material}
            position={[-0.226, 0.191, -0.002]}
            scale={10}
          />
          <mesh
            name="GN_Instance_30"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_30.geometry}
            material={materials.Material}
            position={[0.559, 0.108, -0.112]}
            scale={10}
          />
          <mesh
            name="GN_Instance_31"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_31.geometry}
            material={materials.Material}
            position={[0.53, 0.142, -0.149]}
            scale={10}
          />
          <mesh
            name="GN_Instance_32"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_32.geometry}
            material={materials.Material}
            position={[-0.197, 0.167, -0.006]}
            scale={10}
          />
          <mesh
            name="GN_Instance_33"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_33.geometry}
            material={materials.Material}
            position={[0.478, 0.187, -0.194]}
            scale={10}
          />
          <mesh
            name="GN_Instance_34"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_34.geometry}
            material={materials.Material}
            position={[0.507, 0.179, -0.136]}
            scale={10}
          />
          <mesh
            name="GN_Instance_35"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_35.geometry}
            material={materials.Material}
            position={[0.466, 0.214, -0.132]}
            scale={10}
          />
          <mesh
            name="GN_Instance_36"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_36.geometry}
            material={materials.Material}
            position={[0.386, 0.241, -0.108]}
            scale={10}
          />
          <mesh
            name="GN_Instance_37"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_37.geometry}
            material={materials.Material}
            position={[0.352, 0.243, -0.114]}
            scale={10}
          />
          <mesh
            name="GN_Instance_38"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_38.geometry}
            material={materials.Material}
            position={[0.022, 0.233, 0.449]}
            scale={10}
          />
          <mesh
            name="GN_Instance_39"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_39.geometry}
            material={materials.Material}
            position={[0.077, 0.226, 0.469]}
            scale={10}
          />
          <mesh
            name="GN_Instance_40"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_40.geometry}
            material={materials.Material}
            position={[0.498, 0.086, -0.28]}
            scale={10}
          />
          <mesh
            name="GN_Instance_41"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_41.geometry}
            material={materials.Material}
            position={[0.075, 0.212, 0.493]}
            scale={10}
          />
          <mesh
            name="GN_Instance_42"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_42.geometry}
            material={materials.Material}
            position={[-0.547, 0.069, 0.085]}
            scale={10}
          />
          <mesh
            name="GN_Instance_43"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_43.geometry}
            material={materials.Material}
            position={[0.206, 0.224, 0.204]}
            scale={10}
          />
          <mesh
            name="GN_Instance_44"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_44.geometry}
            material={materials.Material}
            position={[-0.528, 0.097, 0.098]}
            scale={10}
          />
          <mesh
            name="GN_Instance_45"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_45.geometry}
            material={materials.Material}
            position={[-0.489, 0.158, 0.06]}
            scale={10}
          />
          <mesh
            name="GN_Instance_46"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_46.geometry}
            material={materials.Material}
            position={[0.478, 0.172, -0.222]}
            scale={10}
          />
          <mesh
            name="GN_Instance_47"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_47.geometry}
            material={materials.Material}
            position={[0.458, 0.147, -0.289]}
            scale={10}
          />
          <mesh
            name="GN_Instance_48"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_48.geometry}
            material={materials.Material}
            position={[0.456, 0.173, -0.258]}
            scale={10}
          />
          <mesh
            name="GN_Instance_49"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_49.geometry}
            material={materials.Material}
            position={[0.439, 0.219, -0.185]}
            scale={10}
          />
          <mesh
            name="GN_Instance_50"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_50.geometry}
            material={materials.Material}
            position={[0.414, 0.234, -0.171]}
            scale={10}
          />
          <mesh
            name="GN_Instance_51"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_51.geometry}
            material={materials.Material}
            position={[-0.44, 0.198, 0.051]}
            scale={10}
          />
          <mesh
            name="GN_Instance_52"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_52.geometry}
            material={materials.Material}
            position={[0.32, 0.248, -0.182]}
            scale={10}
          />
          <mesh
            name="GN_Instance_53"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_53.geometry}
            material={materials.Material}
            position={[0.281, 0.233, -0.118]}
            scale={10}
          />
          <mesh
            name="GN_Instance_54"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_54.geometry}
            material={materials.Material}
            position={[-0.404, 0.213, 0.064]}
            scale={10}
          />
          <mesh
            name="GN_Instance_55"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_55.geometry}
            material={materials.Material}
            position={[-0.37, 0.227, 0.023]}
            scale={10}
          />
          <mesh
            name="GN_Instance_56"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_56.geometry}
            material={materials.Material}
            position={[-0.313, 0.226, 0.014]}
            scale={10}
          />
          <mesh
            name="GN_Instance_57"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_57.geometry}
            material={materials.Material}
            position={[-0.352, 0.224, 0.067]}
            scale={10}
          />
          <mesh
            name="GN_Instance_58"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_58.geometry}
            material={materials.Material}
            position={[-0.254, 0.205, 0.032]}
            scale={10}
          />
          <mesh
            name="GN_Instance_59"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_59.geometry}
            material={materials.Material}
            position={[0.06, 0.237, 0.443]}
            scale={10}
          />
          <mesh
            name="GN_Instance_60"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_60.geometry}
            material={materials.Material}
            position={[0.443, 0.216, 0.253]}
            scale={10}
          />
          <mesh
            name="GN_Instance_61"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_61.geometry}
            material={materials.Material}
            position={[0.435, 0.122, -0.341]}
            scale={10}
          />
          <mesh
            name="GN_Instance_62"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_62.geometry}
            material={materials.Material}
            position={[0.398, 0.126, -0.377]}
            scale={10}
          />
          <mesh
            name="GN_Instance_63"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_63.geometry}
            material={materials.Material}
            position={[-0.152, 0.107, 0.015]}
            scale={10}
          />
          <mesh
            name="GN_Instance_64"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_64.geometry}
            material={materials.Material}
            position={[0.358, 0.208, -0.325]}
            scale={10}
          />
          <mesh
            name="GN_Instance_65"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_65.geometry}
            material={materials.Material}
            position={[0.402, 0.203, -0.284]}
            scale={10}
          />
          <mesh
            name="GN_Instance_66"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_66.geometry}
            material={materials.Material}
            position={[0.378, 0.22, -0.277]}
            scale={10}
          />
          <mesh
            name="GN_Instance_67"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_67.geometry}
            material={materials.Material}
            position={[0.371, 0.23, -0.255]}
            scale={10}
          />
          <mesh
            name="GN_Instance_68"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_68.geometry}
            material={materials.Material}
            position={[0.29, 0.248, -0.251]}
            scale={10}
          />
          <mesh
            name="GN_Instance_69"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_69.geometry}
            material={materials.Material}
            position={[0.319, 0.247, -0.227]}
            scale={10}
          />
          <mesh
            name="GN_Instance_70"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_70.geometry}
            material={materials.Material}
            position={[0.274, 0.247, -0.202]}
            scale={10}
          />
          <mesh
            name="GN_Instance_71"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_71.geometry}
            material={materials.Material}
            position={[0.225, 0.235, -0.187]}
            scale={10}
          />
          <mesh
            name="GN_Instance_72"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_72.geometry}
            material={materials.Material}
            position={[0.189, 0.219, -0.172]}
            scale={10}
          />
          <mesh
            name="GN_Instance_73"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_73.geometry}
            material={materials.Material}
            position={[0.139, 0.173, -0.135]}
            scale={10}
          />
          <mesh
            name="GN_Instance_74"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_74.geometry}
            material={materials.Material}
            position={[0.011, 0.24, 0.425]}
            scale={10}
          />
          <mesh
            name="GN_Instance_75"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_75.geometry}
            material={materials.Material}
            position={[-0.535, 0.063, 0.157]}
            scale={10}
          />
          <mesh
            name="GN_Instance_76"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_76.geometry}
            material={materials.Material}
            position={[0.009, 0.246, 0.358]}
            scale={10}
          />
          <mesh
            name="GN_Instance_77"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_77.geometry}
            material={materials.Material}
            position={[0.348, 0.099, -0.444]}
            scale={10}
          />
          <mesh
            name="GN_Instance_78"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_78.geometry}
            material={materials.Material}
            position={[0.386, 0.098, -0.409]}
            scale={10}
          />
          <mesh
            name="GN_Instance_79"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_79.geometry}
            material={materials.Material}
            position={[0.364, 0.12, -0.419]}
            scale={10}
          />
          <mesh
            name="GN_Instance_80"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_80.geometry}
            material={materials.Material}
            position={[-0.445, 0.176, 0.205]}
            scale={10}
          />
          <mesh
            name="GN_Instance_81"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_81.geometry}
            material={materials.Material}
            position={[0.323, 0.167, -0.419]}
            scale={10}
          />
          <mesh
            name="GN_Instance_82"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_82.geometry}
            material={materials.Material}
            position={[0.342, 0.146, -0.421]}
            scale={10}
          />
          <mesh
            name="GN_Instance_83"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_83.geometry}
            material={materials.Material}
            position={[-0.423, 0.2, 0.114]}
            scale={10}
          />
          <mesh
            name="GN_Instance_84"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_84.geometry}
            material={materials.Material}
            position={[0.3, 0.214, -0.371]}
            scale={10}
          />
          <mesh
            name="GN_Instance_85"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_85.geometry}
            material={materials.Material}
            position={[0.315, 0.223, -0.338]}
            scale={10}
          />
          <mesh
            name="GN_Instance_86"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_86.geometry}
            material={materials.Material}
            position={[0.26, 0.221, -0.388]}
            scale={10}
          />
          <mesh
            name="GN_Instance_87"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_87.geometry}
            material={materials.Material}
            position={[0.287, 0.241, -0.308]}
            scale={10}
          />
          <mesh
            name="GN_Instance_88"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_88.geometry}
            material={materials.Material}
            position={[-0.344, 0.221, 0.146]}
            scale={10}
          />
          <mesh
            name="GN_Instance_89"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_89.geometry}
            material={materials.Material}
            position={[0.251, 0.249, -0.274]}
            scale={10}
          />
          <mesh
            name="GN_Instance_90"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_90.geometry}
            material={materials.Material}
            position={[0.06, 0.245, 0.331]}
            scale={10}
          />
          <mesh
            name="GN_Instance_91"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_91.geometry}
            material={materials.Material}
            position={[-0.26, 0.211, 0.114]}
            scale={10}
          />
          <mesh
            name="GN_Instance_92"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_92.geometry}
            material={materials.Material}
            position={[-0.281, 0.215, 0.069]}
            scale={10}
          />
          <mesh
            name="GN_Instance_93"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_93.geometry}
            material={materials.Material}
            position={[0.295, 0.127, -0.466]}
            scale={10}
          />
          <mesh
            name="GN_Instance_94"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_94.geometry}
            material={materials.Material}
            position={[0.318, 0.112, -0.459]}
            scale={10}
          />
          <mesh
            name="GN_Instance_95"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_95.geometry}
            material={materials.Material}
            position={[-0.223, 0.188, 0.059]}
            scale={10}
          />
          <mesh
            name="GN_Instance_96"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_96.geometry}
            material={materials.Material}
            position={[0.045, 0.232, 0.288]}
            scale={10}
          />
          <mesh
            name="GN_Instance_97"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_97.geometry}
            material={materials.Material}
            position={[0.456, 0.213, 0.228]}
            scale={10}
          />
          <mesh
            name="GN_Instance_98"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_98.geometry}
            material={materials.Material}
            position={[0.237, 0.187, -0.453]}
            scale={10}
          />
          <mesh
            name="GN_Instance_99"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_99.geometry}
            material={materials.Material}
            position={[0.552, 0.166, 0.059]}
            scale={10}
          />
          <mesh
            name="GN_Instance_100"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_100.geometry}
            material={materials.Material}
            position={[0.272, 0.195, -0.423]}
            scale={10}
          />
          <mesh
            name="GN_Instance_101"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_101.geometry}
            material={materials.Material}
            position={[0.183, 0.231, -0.413]}
            scale={10}
          />
          <mesh
            name="GN_Instance_102"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_102.geometry}
            material={materials.Material}
            position={[0.41, 0.226, 0.206]}
            scale={10}
          />
          <mesh
            name="GN_Instance_103"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_103.geometry}
            material={materials.Material}
            position={[0.175, 0.252, -0.326]}
            scale={10}
          />
          <mesh
            name="GN_Instance_104"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_104.geometry}
            material={materials.Material}
            position={[0.384, 0.227, 0.159]}
            scale={10}
          />
          <mesh
            name="GN_Instance_105"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_105.geometry}
            material={materials.Material}
            position={[0.22, 0.243, -0.356]}
            scale={10}
          />
          <mesh
            name="GN_Instance_106"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_106.geometry}
            material={materials.Material}
            position={[0.203, 0.251, -0.299]}
            scale={10}
          />
          <mesh
            name="GN_Instance_107"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_107.geometry}
            material={materials.Material}
            position={[0.441, 0.22, 0.085]}
            scale={10}
          />
          <mesh
            name="GN_Instance_108"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_108.geometry}
            material={materials.Material}
            position={[0.149, 0.247, -0.273]}
            scale={10}
          />
          <mesh
            name="GN_Instance_109"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_109.geometry}
            material={materials.Material}
            position={[0.512, 0.071, 0.384]}
            scale={10}
          />
          <mesh
            name="GN_Instance_110"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_110.geometry}
            material={materials.Material}
            position={[-0.48, 0.079, 0.333]}
            scale={10}
          />
          <mesh
            name="GN_Instance_111"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_111.geometry}
            material={materials.Material}
            position={[0.279, 0.226, 0.169]}
            scale={10}
          />
          <mesh
            name="GN_Instance_112"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_112.geometry}
            material={materials.Material}
            position={[0.081, 0.131, -0.14]}
            scale={10}
          />
          <mesh
            name="GN_Instance_113"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_113.geometry}
            material={materials.Material}
            position={[0.178, 0.085, -0.524]}
            scale={10}
          />
          <mesh
            name="GN_Instance_114"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_114.geometry}
            material={materials.Material}
            position={[-0.51, -0.106, 0.317]}
            scale={10}
          />
          <mesh
            name="GN_Instance_115"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_115.geometry}
            material={materials.Material}
            position={[0.191, 0.174, -0.484]}
            scale={10}
          />
          <mesh
            name="GN_Instance_116"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_116.geometry}
            material={materials.Material}
            position={[0.112, 0.134, -0.524]}
            scale={10}
          />
          <mesh
            name="GN_Instance_117"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_117.geometry}
            material={materials.Material}
            position={[0.155, 0.161, -0.503]}
            scale={10}
          />
          <mesh
            name="GN_Instance_118"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_118.geometry}
            material={materials.Material}
            position={[-0.46, 0.16, 0.222]}
            scale={10}
          />
          <mesh
            name="GN_Instance_119"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_119.geometry}
            material={materials.Material}
            position={[0.121, 0.171, -0.504]}
            scale={10}
          />
          <mesh
            name="GN_Instance_120"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_120.geometry}
            material={materials.Material}
            position={[0.141, 0.185, -0.49]}
            scale={10}
          />
          <mesh
            name="GN_Instance_121"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_121.geometry}
            material={materials.Material}
            position={[0.449, 0.125, 0.418]}
            scale={10}
          />
          <mesh
            name="GN_Instance_122"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_122.geometry}
            material={materials.Material}
            position={[0.143, 0.239, -0.408]}
            scale={10}
          />
          <mesh
            name="GN_Instance_123"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_123.geometry}
            material={materials.Material}
            position={[0.111, 0.251, -0.371]}
            scale={10}
          />
          <mesh
            name="GN_Instance_124"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_124.geometry}
            material={materials.Material}
            position={[-0.339, 0.222, 0.228]}
            scale={10}
          />
          <mesh
            name="GN_Instance_125"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_125.geometry}
            material={materials.Material}
            position={[0.365, 0.225, 0.045]}
            scale={10}
          />
          <mesh
            name="GN_Instance_126"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_126.geometry}
            material={materials.Material}
            position={[-0.225, 0.199, 0.124]}
            scale={10}
          />
          <mesh
            name="GN_Instance_127"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_127.geometry}
            material={materials.Material}
            position={[-0.19, 0.179, 0.118]}
            scale={10}
          />
          <mesh
            name="GN_Instance_128"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_128.geometry}
            material={materials.Material}
            position={[0.081, 0.251, -0.299]}
            scale={10}
          />
          <mesh
            name="GN_Instance_129"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_129.geometry}
            material={materials.Material}
            position={[0.078, 0.224, -0.229]}
            scale={10}
          />
          <mesh
            name="GN_Instance_130"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_130.geometry}
            material={materials.Material}
            position={[-0.153, 0.131, 0.084]}
            scale={10}
          />
          <mesh
            name="GN_Instance_131"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_131.geometry}
            material={materials.Material}
            position={[0.086, 0.196, -0.191]}
            scale={10}
          />
          <mesh
            name="GN_Instance_132"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_132.geometry}
            material={materials.Material}
            position={[0.062, 0.109, -0.137]}
            scale={10}
          />
          <mesh
            name="GN_Instance_133"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_133.geometry}
            material={materials.Material}
            position={[0.128, 0.12, 0.563]}
            scale={10}
          />
          <mesh
            name="GN_Instance_134"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_134.geometry}
            material={materials.Material}
            position={[0.458, 0.166, 0.372]}
            scale={10}
          />
          <mesh
            name="GN_Instance_135"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_135.geometry}
            material={materials.Material}
            position={[0.504, 0.2, 0.009]}
            scale={10}
          />
          <mesh
            name="GN_Instance_136"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_136.geometry}
            material={materials.Material}
            position={[0.198, 0.196, 0.494]}
            scale={10}
          />
          <mesh
            name="GN_Instance_137"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_137.geometry}
            material={materials.Material}
            position={[0.039, 0.168, -0.516]}
            scale={10}
          />
          <mesh
            name="GN_Instance_138"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_138.geometry}
            material={materials.Material}
            position={[0.038, 0.201, -0.489]}
            scale={10}
          />
          <mesh
            name="GN_Instance_139"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_139.geometry}
            material={materials.Material}
            position={[0.13, 0.24, 0.432]}
            scale={10}
          />
          <mesh
            name="GN_Instance_140"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_140.geometry}
            material={materials.Material}
            position={[0.091, 0.196, -0.489]}
            scale={10}
          />
          <mesh
            name="GN_Instance_141"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_141.geometry}
            material={materials.Material}
            position={[0.162, 0.232, 0.445]}
            scale={10}
          />
          <mesh
            name="GN_Instance_142"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_142.geometry}
            material={materials.Material}
            position={[-0.448, 0.121, 0.353]}
            scale={10}
          />
          <mesh
            name="GN_Instance_143"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_143.geometry}
            material={materials.Material}
            position={[0.069, 0.217, -0.466]}
            scale={10}
          />
          <mesh
            name="GN_Instance_144"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_144.geometry}
            material={materials.Material}
            position={[0.084, 0.227, -0.449]}
            scale={10}
          />
          <mesh
            name="GN_Instance_145"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_145.geometry}
            material={materials.Material}
            position={[0.055, 0.228, -0.449]}
            scale={10}
          />
          <mesh
            name="GN_Instance_146"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_146.geometry}
            material={materials.Material}
            position={[0.062, 0.246, -0.404]}
            scale={10}
          />
          <mesh
            name="GN_Instance_147"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_147.geometry}
            material={materials.Material}
            position={[0.171, 0.241, 0.42]}
            scale={10}
          />
          <mesh
            name="GN_Instance_148"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_148.geometry}
            material={materials.Material}
            position={[0.076, 0.252, -0.373]}
            scale={10}
          />
          <mesh
            name="GN_Instance_149"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_149.geometry}
            material={materials.Material}
            position={[0.044, 0.251, -0.296]}
            scale={10}
          />
          <mesh
            name="GN_Instance_150"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_150.geometry}
            material={materials.Material}
            position={[0.473, 0.173, 0.345]}
            scale={10}
          />
          <mesh
            name="GN_Instance_151"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_151.geometry}
            material={materials.Material}
            position={[0.027, 0.188, -0.192]}
            scale={10}
          />
          <mesh
            name="GN_Instance_152"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_152.geometry}
            material={materials.Material}
            position={[0.008, 0.203, -0.206]}
            scale={10}
          />
          <mesh
            name="GN_Instance_153"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_153.geometry}
            material={materials.Material}
            position={[0.107, 0.249, 0.39]}
            scale={10}
          />
          <mesh
            name="GN_Instance_154"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_154.geometry}
            material={materials.Material}
            position={[-0.425, 0.171, 0.313]}
            scale={10}
          />
          <mesh
            name="GN_Instance_155"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_155.geometry}
            material={materials.Material}
            position={[-0.408, 0.189, 0.294]}
            scale={10}
          />
          <mesh
            name="GN_Instance_156"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_156.geometry}
            material={materials.Material}
            position={[-0.212, 0.214, 0.193]}
            scale={10}
          />
          <mesh
            name="GN_Instance_157"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_157.geometry}
            material={materials.Material}
            position={[-0.058, 0.097, -0.547]}
            scale={10}
          />
          <mesh
            name="GN_Instance_158"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_158.geometry}
            material={materials.Material}
            position={[-0.079, 0.077, -0.55]}
            scale={10}
          />
          <mesh
            name="GN_Instance_159"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_159.geometry}
            material={materials.Material}
            position={[-0.038, 0.171, -0.514]}
            scale={10}
          />
          <mesh
            name="GN_Instance_160"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_160.geometry}
            material={materials.Material}
            position={[-0.015, 0.233, -0.439]}
            scale={10}
          />
          <mesh
            name="GN_Instance_161"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_161.geometry}
            material={materials.Material}
            position={[-0.241, 0.219, 0.192]}
            scale={10}
          />
          <mesh
            name="GN_Instance_162"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_162.geometry}
            material={materials.Material}
            position={[-0.016, 0.244, -0.411]}
            scale={10}
          />
          <mesh
            name="GN_Instance_163"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_163.geometry}
            material={materials.Material}
            position={[-0.064, 0.229, -0.443]}
            scale={10}
          />
          <mesh
            name="GN_Instance_164"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_164.geometry}
            material={materials.Material}
            position={[0.088, 0.246, 0.329]}
            scale={10}
          />
          <mesh
            name="GN_Instance_165"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_165.geometry}
            material={materials.Material}
            position={[0.096, 0.25, 0.362]}
            scale={10}
          />
          <mesh
            name="GN_Instance_166"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_166.geometry}
            material={materials.Material}
            position={[-0.059, 0.251, -0.378]}
            scale={10}
          />
          <mesh
            name="GN_Instance_167"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_167.geometry}
            material={materials.Material}
            position={[0.53, 0.185, 0.093]}
            scale={10}
          />
          <mesh
            name="GN_Instance_168"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_168.geometry}
            material={materials.Material}
            position={[0.097, 0.234, 0.28]}
            scale={10}
          />
          <mesh
            name="GN_Instance_169"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_169.geometry}
            material={materials.Material}
            position={[-0.005, 0.254, -0.359]}
            scale={10}
          />
          <mesh
            name="GN_Instance_170"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_170.geometry}
            material={materials.Material}
            position={[-0.356, 0.086, 0.471]}
            scale={10}
          />
          <mesh
            name="GN_Instance_171"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_171.geometry}
            material={materials.Material}
            position={[-0.033, 0.253, -0.371]}
            scale={10}
          />
          <mesh
            name="GN_Instance_172"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_172.geometry}
            material={materials.Material}
            position={[-0.014, 0.252, -0.302]}
            scale={10}
          />
          <mesh
            name="GN_Instance_173"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_173.geometry}
            material={materials.Material}
            position={[-0.067, 0.254, -0.331]}
            scale={10}
          />
          <mesh
            name="GN_Instance_174"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_174.geometry}
            material={materials.Material}
            position={[-0.036, 0.254, -0.318]}
            scale={10}
          />
          <mesh
            name="GN_Instance_175"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_175.geometry}
            material={materials.Material}
            position={[-0.052, 0.245, -0.274]}
            scale={10}
          />
          <mesh
            name="GN_Instance_176"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_176.geometry}
            material={materials.Material}
            position={[-0.018, 0.194, -0.197]}
            scale={10}
          />
          <mesh
            name="GN_Instance_177"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_177.geometry}
            material={materials.Material}
            position={[0.484, 0.14, 0.374]}
            scale={10}
          />
          <mesh
            name="GN_Instance_178"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_178.geometry}
            material={materials.Material}
            position={[-0.025, 0.166, -0.175]}
            scale={10}
          />
          <mesh
            name="GN_Instance_179"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_179.geometry}
            material={materials.Material}
            position={[0.055, 0.213, 0.247]}
            scale={10}
          />
          <mesh
            name="GN_Instance_180"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_180.geometry}
            material={materials.Material}
            position={[-0.375, 0.157, 0.406]}
            scale={10}
          />
          <mesh
            name="GN_Instance_181"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_181.geometry}
            material={materials.Material}
            position={[-0.019, 0.111, -0.145]}
            scale={10}
          />
          <mesh
            name="GN_Instance_182"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_182.geometry}
            material={materials.Material}
            position={[-0.291, 0.208, 0.406]}
            scale={10}
          />
          <mesh
            name="GN_Instance_183"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_183.geometry}
            material={materials.Material}
            position={[-0.283, 0.225, 0.363]}
            scale={10}
          />
          <mesh
            name="GN_Instance_184"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_184.geometry}
            material={materials.Material}
            position={[-0.189, 0.001, -0.54]}
            scale={10}
          />
          <mesh
            name="GN_Instance_185"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_185.geometry}
            material={materials.Material}
            position={[0.38, 0.224, 0.327]}
            scale={10}
          />
          <mesh
            name="GN_Instance_186"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_186.geometry}
            material={materials.Material}
            position={[0.049, 0.168, 0.188]}
            scale={10}
          />
          <mesh
            name="GN_Instance_187"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_187.geometry}
            material={materials.Material}
            position={[-0.164, 0.023, -0.545]}
            scale={10}
          />
          <mesh
            name="GN_Instance_188"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_188.geometry}
            material={materials.Material}
            position={[-0.213, 0.231, 0.258]}
            scale={10}
          />
          <mesh
            name="GN_Instance_189"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_189.geometry}
            material={materials.Material}
            position={[-0.179, 0.223, 0.238]}
            scale={10}
          />
          <mesh
            name="GN_Instance_190"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_190.geometry}
            material={materials.Material}
            position={[0.402, 0.225, 0.288]}
            scale={10}
          />
          <mesh
            name="GN_Instance_191"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_191.geometry}
            material={materials.Material}
            position={[-0.143, 0.13, -0.524]}
            scale={10}
          />
          <mesh
            name="GN_Instance_192"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_192.geometry}
            material={materials.Material}
            position={[-0.107, 0.104, -0.541]}
            scale={10}
          />
          <mesh
            name="GN_Instance_193"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_193.geometry}
            material={materials.Material}
            position={[0.591, 0.111, 0.14]}
            scale={10}
          />
          <mesh
            name="GN_Instance_194"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_194.geometry}
            material={materials.Material}
            position={[-0.141, 0.177, 0.166]}
            scale={10}
          />
          <mesh
            name="GN_Instance_195"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_195.geometry}
            material={materials.Material}
            position={[-0.18, 0.167, -0.489]}
            scale={10}
          />
          <mesh
            name="GN_Instance_196"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_196.geometry}
            material={materials.Material}
            position={[-0.171, 0.207, -0.451]}
            scale={10}
          />
          <mesh
            name="GN_Instance_197"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_197.geometry}
            material={materials.Material}
            position={[-0.107, 0.167, -0.509]}
            scale={10}
          />
          <mesh
            name="GN_Instance_198"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_198.geometry}
            material={materials.Material}
            position={[-0.147, 0.176, -0.492]}
            scale={10}
          />
          <mesh
            name="GN_Instance_199"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_199.geometry}
            material={materials.Material}
            position={[0.374, 0.231, 0.292]}
            scale={10}
          />
          <mesh
            name="GN_Instance_200"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_200.geometry}
            material={materials.Material}
            position={[-0.115, 0.215, -0.457]}
            scale={10}
          />
          <mesh
            name="GN_Instance_201"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_201.geometry}
            material={materials.Material}
            position={[-0.113, 0.239, -0.411]}
            scale={10}
          />
          <mesh
            name="GN_Instance_202"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_202.geometry}
            material={materials.Material}
            position={[0.321, 0.237, 0.227]}
            scale={10}
          />
          <mesh
            name="GN_Instance_203"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_203.geometry}
            material={materials.Material}
            position={[-0.147, 0.23, -0.423]}
            scale={10}
          />
          <mesh
            name="GN_Instance_204"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_204.geometry}
            material={materials.Material}
            position={[-0.089, 0.248, -0.384]}
            scale={10}
          />
          <mesh
            name="GN_Instance_205"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_205.geometry}
            material={materials.Material}
            position={[0.33, 0.24, 0.274]}
            scale={10}
          />
          <mesh
            name="GN_Instance_206"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_206.geometry}
            material={materials.Material}
            position={[-0.09, 0.249, -0.29]}
            scale={10}
          />
          <mesh
            name="GN_Instance_207"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_207.geometry}
            material={materials.Material}
            position={[-0.237, 0.118, 0.515]}
            scale={10}
          />
          <mesh
            name="GN_Instance_208"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_208.geometry}
            material={materials.Material}
            position={[0.286, 0.244, 0.279]}
            scale={10}
          />
          <mesh
            name="GN_Instance_209"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_209.geometry}
            material={materials.Material}
            position={[-0.075, 0.237, -0.252]}
            scale={10}
          />
          <mesh
            name="GN_Instance_210"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_210.geometry}
            material={materials.Material}
            position={[0.251, 0.086, 0.542]}
            scale={10}
          />
          <mesh
            name="GN_Instance_211"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_211.geometry}
            material={materials.Material}
            position={[0.308, 0.242, 0.298]}
            scale={10}
          />
          <mesh
            name="GN_Instance_212"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_212.geometry}
            material={materials.Material}
            position={[0.492, 0.206, 0.073]}
            scale={10}
          />
          <mesh
            name="GN_Instance_213"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_213.geometry}
            material={materials.Material}
            position={[-0.056, 0.159, -0.166]}
            scale={10}
          />
          <mesh
            name="GN_Instance_214"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_214.geometry}
            material={materials.Material}
            position={[0.587, 0.091, 0.208]}
            scale={10}
          />
          <mesh
            name="GN_Instance_215"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_215.geometry}
            material={materials.Material}
            position={[-0.171, 0.231, 0.413]}
            scale={10}
          />
          <mesh
            name="GN_Instance_216"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_216.geometry}
            material={materials.Material}
            position={[0.277, 0.194, 0.463]}
            scale={10}
          />
          <mesh
            name="GN_Instance_217"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_217.geometry}
            material={materials.Material}
            position={[-0.147, 0.239, 0.309]}
            scale={10}
          />
          <mesh
            name="GN_Instance_218"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_218.geometry}
            material={materials.Material}
            position={[0.263, 0.229, 0.191]}
            scale={10}
          />
          <mesh
            name="GN_Instance_219"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_219.geometry}
            material={materials.Material}
            position={[0.294, 0.201, 0.445]}
            scale={10}
          />
          <mesh
            name="GN_Instance_220"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_220.geometry}
            material={materials.Material}
            position={[-0.14, 0.225, 0.256]}
            scale={10}
          />
          <mesh
            name="GN_Instance_221"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_221.geometry}
            material={materials.Material}
            position={[-0.105, 0.204, 0.223]}
            scale={10}
          />
          <mesh
            name="GN_Instance_222"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_222.geometry}
            material={materials.Material}
            position={[0.57, 0.126, 0.212]}
            scale={10}
          />
          <mesh
            name="GN_Instance_223"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_223.geometry}
            material={materials.Material}
            position={[0.268, 0.219, 0.43]}
            scale={10}
          />
          <mesh
            name="GN_Instance_224"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_224.geometry}
            material={materials.Material}
            position={[-0.278, 0.193, -0.412]}
            scale={10}
          />
          <mesh
            name="GN_Instance_225"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_225.geometry}
            material={materials.Material}
            position={[0.231, 0.244, 0.378]}
            scale={10}
          />
          <mesh
            name="GN_Instance_226"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_226.geometry}
            material={materials.Material}
            position={[-0.242, 0.178, -0.452]}
            scale={10}
          />
          <mesh
            name="GN_Instance_227"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_227.geometry}
            material={materials.Material}
            position={[-0.194, 0.188, -0.465]}
            scale={10}
          />
          <mesh
            name="GN_Instance_228"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_228.geometry}
            material={materials.Material}
            position={[-0.134, 0.115, 0.552]}
            scale={10}
          />
          <mesh
            name="GN_Instance_229"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_229.geometry}
            material={materials.Material}
            position={[-0.187, 0.233, -0.399]}
            scale={10}
          />
          <mesh
            name="GN_Instance_230"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_230.geometry}
            material={materials.Material}
            position={[-0.224, 0.237, -0.369]}
            scale={10}
          />
          <mesh
            name="GN_Instance_231"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_231.geometry}
            material={materials.Material}
            position={[0.166, 0.25, 0.341]}
            scale={10}
          />
          <mesh
            name="GN_Instance_232"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_232.geometry}
            material={materials.Material}
            position={[-0.202, 0.251, -0.31]}
            scale={10}
          />
          <mesh
            name="GN_Instance_233"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_233.geometry}
            material={materials.Material}
            position={[0.161, 0.247, 0.311]}
            scale={10}
          />
          <mesh
            name="GN_Instance_234"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_234.geometry}
            material={materials.Material}
            position={[-0.197, 0.248, -0.341]}
            scale={10}
          />
          <mesh
            name="GN_Instance_235"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_235.geometry}
            material={materials.Material}
            position={[0.215, 0.204, 0.14]}
            scale={10}
          />
          <mesh
            name="GN_Instance_236"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_236.geometry}
            material={materials.Material}
            position={[-0.162, 0.251, -0.296]}
            scale={10}
          />
          <mesh
            name="GN_Instance_237"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_237.geometry}
            material={materials.Material}
            position={[-0.135, 0.252, -0.304]}
            scale={10}
          />
          <mesh
            name="GN_Instance_238"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_238.geometry}
            material={materials.Material}
            position={[-0.089, 0.237, 0.412]}
            scale={10}
          />
          <mesh
            name="GN_Instance_239"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_239.geometry}
            material={materials.Material}
            position={[-0.19, 0.251, -0.286]}
            scale={10}
          />
          <mesh
            name="GN_Instance_240"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_240.geometry}
            material={materials.Material}
            position={[-0.122, 0.233, -0.236]}
            scale={10}
          />
          <mesh
            name="GN_Instance_241"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_241.geometry}
            material={materials.Material}
            position={[-0.143, 0.241, -0.253]}
            scale={10}
          />
          <mesh
            name="GN_Instance_242"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_242.geometry}
            material={materials.Material}
            position={[-0.087, 0.183, -0.177]}
            scale={10}
          />
          <mesh
            name="GN_Instance_243"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_243.geometry}
            material={materials.Material}
            position={[-0.129, 0.218, -0.207]}
            scale={10}
          />
          <mesh
            name="GN_Instance_244"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_244.geometry}
            material={materials.Material}
            position={[0.156, 0.242, 0.286]}
            scale={10}
          />
          <mesh
            name="GN_Instance_245"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_245.geometry}
            material={materials.Material}
            position={[-0.131, 0.242, 0.371]}
            scale={10}
          />
          <mesh
            name="GN_Instance_246"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_246.geometry}
            material={materials.Material}
            position={[0.548, 0.166, 0.166]}
            scale={10}
          />
          <mesh
            name="GN_Instance_247"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_247.geometry}
            material={materials.Material}
            position={[-0.114, 0.234, 0.291]}
            scale={10}
          />
          <mesh
            name="GN_Instance_248"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_248.geometry}
            material={materials.Material}
            position={[-0.081, 0.189, 0.21]}
            scale={10}
          />
          <mesh
            name="GN_Instance_249"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_249.geometry}
            material={materials.Material}
            position={[-0.358, 0.139, -0.4]}
            scale={10}
          />
          <mesh
            name="GN_Instance_250"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_250.geometry}
            material={materials.Material}
            position={[-0.389, 0.135, -0.374]}
            scale={10}
          />
          <mesh
            name="GN_Instance_251"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_251.geometry}
            material={materials.Material}
            position={[0.125, 0.232, 0.265]}
            scale={10}
          />
          <mesh
            name="GN_Instance_252"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_252.geometry}
            material={materials.Material}
            position={[-0.343, 0.182, -0.372]}
            scale={10}
          />
          <mesh
            name="GN_Instance_253"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_253.geometry}
            material={materials.Material}
            position={[0.082, 0.178, 0.187]}
            scale={10}
          />
          <mesh
            name="GN_Instance_254"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_254.geometry}
            material={materials.Material}
            position={[-0.053, 0.161, 0.185]}
            scale={10}
          />
          <mesh
            name="GN_Instance_255"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_255.geometry}
            material={materials.Material}
            position={[-0.259, 0.25, -0.275]}
            scale={10}
          />
          <mesh
            name="GN_Instance_256"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_256.geometry}
            material={materials.Material}
            position={[-0.265, 0.242, -0.32]}
            scale={10}
          />
          <mesh
            name="GN_Instance_257"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_257.geometry}
            material={materials.Material}
            position={[-0.219, 0.25, -0.262]}
            scale={10}
          />
          <mesh
            name="GN_Instance_258"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_258.geometry}
            material={materials.Material}
            position={[0.473, 0.211, 0.108]}
            scale={10}
          />
          <mesh
            name="GN_Instance_259"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_259.geometry}
            material={materials.Material}
            position={[-0.198, 0.238, -0.215]}
            scale={10}
          />
          <mesh
            name="GN_Instance_260"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_260.geometry}
            material={materials.Material}
            position={[-0.18, 0.219, -0.181]}
            scale={10}
          />
          <mesh
            name="GN_Instance_261"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_261.geometry}
            material={materials.Material}
            position={[0.483, 0.207, 0.134]}
            scale={10}
          />
          <mesh
            name="GN_Instance_262"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_262.geometry}
            material={materials.Material}
            position={[0.259, 0.201, 0.021]}
            scale={10}
          />
          <mesh
            name="GN_Instance_263"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_263.geometry}
            material={materials.Material}
            position={[-0.124, 0.151, -0.123]}
            scale={10}
          />
          <mesh
            name="GN_Instance_264"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_264.geometry}
            material={materials.Material}
            position={[-0.095, 0.103, -0.099]}
            scale={10}
          />
          <mesh
            name="GN_Instance_265"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_265.geometry}
            material={materials.Material}
            position={[0.393, 0.229, 0.005]}
            scale={10}
          />
          <mesh
            name="GN_Instance_266"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_266.geometry}
            material={materials.Material}
            position={[0.585, 0.119, 0.043]}
            scale={10}
          />
          <mesh
            name="GN_Instance_267"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_267.geometry}
            material={materials.Material}
            position={[0.421, 0.085, 0.459]}
            scale={10}
          />
          <mesh
            name="GN_Instance_268"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_268.geometry}
            material={materials.Material}
            position={[0.426, 0.223, 0.058]}
            scale={10}
          />
          <mesh
            name="GN_Instance_269"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_269.geometry}
            material={materials.Material}
            position={[-0.025, 0.145, 0.556]}
            scale={10}
          />
          <mesh
            name="GN_Instance_270"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_270.geometry}
            material={materials.Material}
            position={[-0.427, 0.141, -0.33]}
            scale={10}
          />
          <mesh
            name="GN_Instance_271"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_271.geometry}
            material={materials.Material}
            position={[-0.385, 0.21, -0.287]}
            scale={10}
          />
          <mesh
            name="GN_Instance_272"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_272.geometry}
            material={materials.Material}
            position={[-0.361, 0.235, -0.25]}
            scale={10}
          />
          <mesh
            name="GN_Instance_273"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_273.geometry}
            material={materials.Material}
            position={[0.373, 0.126, 0.47]}
            scale={10}
          />
          <mesh
            name="GN_Instance_274"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_274.geometry}
            material={materials.Material}
            position={[-0.307, 0.246, -0.258]}
            scale={10}
          />
          <mesh
            name="GN_Instance_275"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_275.geometry}
            material={materials.Material}
            position={[-0.083, 0.171, 0.525]}
            scale={10}
          />
          <mesh
            name="GN_Instance_276"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_276.geometry}
            material={materials.Material}
            position={[-0.066, 0.21, 0.481]}
            scale={10}
          />
          <mesh
            name="GN_Instance_277"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_277.geometry}
            material={materials.Material}
            position={[-0.264, 0.247, -0.199]}
            scale={10}
          />
          <mesh
            name="GN_Instance_278"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_278.geometry}
            material={materials.Material}
            position={[-0.217, 0.221, -0.148]}
            scale={10}
          />
          <mesh
            name="GN_Instance_279"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_279.geometry}
            material={materials.Material}
            position={[-0.189, 0.211, -0.154]}
            scale={10}
          />
          <mesh
            name="GN_Instance_280"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_280.geometry}
            material={materials.Material}
            position={[0.532, 0.173, 0.222]}
            scale={10}
          />
          <mesh
            name="GN_Instance_281"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_281.geometry}
            material={materials.Material}
            position={[-0.079, 0.227, 0.445]}
            scale={10}
          />
          <mesh
            name="GN_Instance_282"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_282.geometry}
            material={materials.Material}
            position={[-0.019, 0.237, 0.429]}
            scale={10}
          />
          <mesh
            name="GN_Instance_283"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_283.geometry}
            material={materials.Material}
            position={[-0.051, 0.235, 0.43]}
            scale={10}
          />
          <mesh
            name="GN_Instance_284"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_284.geometry}
            material={materials.Material}
            position={[-0.049, 0.242, 0.4]}
            scale={10}
          />
          <mesh
            name="GN_Instance_285"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_285.geometry}
            material={materials.Material}
            position={[-0.468, 0.17, -0.245]}
            scale={10}
          />
          <mesh
            name="GN_Instance_286"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_286.geometry}
            material={materials.Material}
            position={[0.405, 0.111, 0.459]}
            scale={10}
          />
          <mesh
            name="GN_Instance_287"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_287.geometry}
            material={materials.Material}
            position={[-0.475, 0.182, -0.207]}
            scale={10}
          />
          <mesh
            name="GN_Instance_288"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_288.geometry}
            material={materials.Material}
            position={[-0.377, 0.235, -0.229]}
            scale={10}
          />
          <mesh
            name="GN_Instance_289"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_289.geometry}
            material={materials.Material}
            position={[-0.426, 0.226, -0.169]}
            scale={10}
          />
          <mesh
            name="GN_Instance_290"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_290.geometry}
            material={materials.Material}
            position={[-0.346, 0.248, -0.177]}
            scale={10}
          />
          <mesh
            name="GN_Instance_291"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_291.geometry}
            material={materials.Material}
            position={[-0.332, 0.249, -0.205]}
            scale={10}
          />
          <mesh
            name="GN_Instance_292"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_292.geometry}
            material={materials.Material}
            position={[0.4, 0.144, 0.441]}
            scale={10}
          />
          <mesh
            name="GN_Instance_293"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_293.geometry}
            material={materials.Material}
            position={[-0.217, 0.202, -0.09]}
            scale={10}
          />
          <mesh
            name="GN_Instance_294"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_294.geometry}
            material={materials.Material}
            position={[0.328, 0.193, 0.437]}
            scale={10}
          />
          <mesh
            name="GN_Instance_295"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_295.geometry}
            material={materials.Material}
            position={[-0.05, 0.244, 0.354]}
            scale={10}
          />
          <mesh
            name="GN_Instance_296"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_296.geometry}
            material={materials.Material}
            position={[-0.059, 0.24, 0.322]}
            scale={10}
          />
          <mesh
            name="GN_Instance_297"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_297.geometry}
            material={materials.Material}
            position={[-0.01, 0.197, 0.23]}
            scale={10}
          />
          <mesh
            name="GN_Instance_298"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_298.geometry}
            material={materials.Material}
            position={[0.483, 0.204, 0.222]}
            scale={10}
          />
          <mesh
            name="GN_Instance_299"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_299.geometry}
            material={materials.Material}
            position={[0.56, 0.159, 0.092]}
            scale={10}
          />
          <mesh
            name="GN_Instance_300"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_300.geometry}
            material={materials.Material}
            position={[-0.516, 0.156, -0.152]}
            scale={10}
          />
          <mesh
            name="GN_Instance_301"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_301.geometry}
            material={materials.Material}
            position={[0.336, 0.21, 0.406]}
            scale={10}
          />
          <mesh
            name="GN_Instance_302"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_302.geometry}
            material={materials.Material}
            position={[0.288, 0.226, 0.403]}
            scale={10}
          />
          <mesh
            name="GN_Instance_303"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_303.geometry}
            material={materials.Material}
            position={[-0.5, 0.179, -0.116]}
            scale={10}
          />
          <mesh
            name="GN_Instance_304"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_304.geometry}
            material={materials.Material}
            position={[-0.455, 0.207, -0.177]}
            scale={10}
          />
          <mesh
            name="GN_Instance_305"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_305.geometry}
            material={materials.Material}
            position={[-0.451, 0.215, -0.107]}
            scale={10}
          />
          <mesh
            name="GN_Instance_306"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_306.geometry}
            material={materials.Material}
            position={[-0.374, 0.245, -0.146]}
            scale={10}
          />
          <mesh
            name="GN_Instance_307"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_307.geometry}
            material={materials.Material}
            position={[0.362, 0.223, 0.351]}
            scale={10}
          />
          <mesh
            name="GN_Instance_308"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_308.geometry}
            material={materials.Material}
            position={[-0.206, 0.184, -0.052]}
            scale={10}
          />
          <mesh
            name="GN_Instance_309"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_309.geometry}
            material={materials.Material}
            position={[-0.187, 0.168, -0.056]}
            scale={10}
          />
          <mesh
            name="GN_Instance_310"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_310.geometry}
            material={materials.Material}
            position={[0.305, 0.239, 0.344]}
            scale={10}
          />
          <mesh
            name="GN_Instance_311"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_311.geometry}
            material={materials.Material}
            position={[0.494, 0.179, 0.307]}
            scale={10}
          />
          <mesh
            name="GN_Instance_312"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_312.geometry}
            material={materials.Material}
            position={[0.018, 0.155, 0.551]}
            scale={10}
          />
          <mesh
            name="GN_Instance_313"
            castShadow
            receiveShadow
            geometry={nodes.GN_Instance_313.geometry}
            material={materials.Material}
            position={[0.186, 0.241, 0.267]}
            scale={10}
          />
        </mesh>
        <group
          name="Olho_1"
          position={[0.185, 0.29, -0.085]}
          rotation={[2.321, -0.913, 0.558]}
          scale={0.266}>
          <mesh
            name="Mesh_4"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_4.geometry}
            material={materials['Material.002']}
          />
          <mesh
            name="Mesh_5"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_5.geometry}
            material={materials['Material.004']}
          />
        </group>
        <group name="Ufo_Curve" position={[0.022, 0.373, -0.085]} scale={0.22} />
        <group
          name="Olho_2"
          position={[0.215, 0.219, -0.138]}
          rotation={[2.925, -0.578, -1.251]}
          scale={0.375}>
          <mesh
            name="Mesh_6"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_6.geometry}
            material={materials['Material.002']}
          />
          <mesh
            name="Mesh_7"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_7.geometry}
            material={materials['Material.004']}
          />
        </group>
        <group
          name="Olho_3"
          position={[0.161, 0.198, -0.182]}
          rotation={[-1.949, -1.447, -0.765]}
          scale={0.585}>
          <mesh
            name="Mesh_8"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_8.geometry}
            material={materials['Material.002']}
          />
          <mesh
            name="Mesh_9"
            castShadow
            receiveShadow
            geometry={nodes.Mesh_9.geometry}
            material={materials['Material.004']}
          />
        </group>
        <group
          name="Empty"
          position={[-0.048, 0.374, -0.087]}
          rotation={[2.883, -0.796, 2.935]}
          scale={0.024}>
          <group
            name="UFO"
            position={[-0.004, 0.133, -0.065]}
            rotation={[-1.764, 1.255, 1.271]}
            scale={42.254}>
            <mesh
              name="Mesh_10"
              castShadow
              receiveShadow
              geometry={nodes.Mesh_10.geometry}
              material={materials.Vidro}
            />
            <mesh
              name="Mesh_11"
              castShadow
              receiveShadow
              geometry={nodes.Mesh_11.geometry}
              material={materials.Giro}
            />
            <mesh
              name="Mesh_12"
              castShadow
              receiveShadow
              geometry={nodes.Mesh_12.geometry}
              material={materials.Pes}
            />
            <mesh
              name="Mesh_13"
              castShadow
              receiveShadow
              geometry={nodes.Mesh_13.geometry}
              material={materials.Metal}
            />
          </group>
        </group>
        <mesh
          name="Gato"
          castShadow
          receiveShadow
          geometry={nodes.Gato.geometry}
          material={materials['Pelo do Gato']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/Site.glb')